
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int __boolean__ = 2;
  public static final int __division__ = 23;
  public static final int __greaterequal__ = 28;
  public static final int __interface__ = 12;
  public static final int __comma__ = 35;
  public static final int __class__ = 4;
  public static final int __int__ = 11;
  public static final int __not__ = 33;
  public static final int __and__ = 31;
  public static final int __return__ = 16;
  public static final int __period__ = 37;
  public static final int __leftparen__ = 39;
  public static final int __if__ = 9;
  public static final int __rightbrace__ = 44;
  public static final int __or__ = 32;
  public static final int __uminus__ = 38;
  public static final int __mod__ = 24;
  public static final int __semicolon__ = 36;
  public static final int __double__ = 5;
  public static final int __multiplication__ = 22;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int __newarray__ = 13;
  public static final int __id__ = 49;
  public static final int __doubleconstant__ = 46;
  public static final int __plus__ = 20;
  public static final int __readln__ = 15;
  public static final int __less__ = 25;
  public static final int __extends__ = 7;
  public static final int __void__ = 18;
  public static final int __intconstant__ = 45;
  public static final int __for__ = 8;
  public static final int __assignop__ = 34;
  public static final int __stringconstant__ = 47;
  public static final int __println__ = 14;
  public static final int __else__ = 6;
  public static final int __lessequal__ = 26;
  public static final int __notequal__ = 30;
  public static final int __equal__ = 29;
  public static final int __while__ = 19;
  public static final int __break__ = 3;
  public static final int __rightparen__ = 40;
  public static final int __string__ = 17;
  public static final int __implements__ = 10;
  public static final int __greater__ = 27;
  public static final int __rightbracket__ = 42;
  public static final int __booleanconstant__ = 48;
  public static final int __leftbracket__ = 41;
  public static final int __leftbrace__ = 43;
  public static final int __minus__ = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "__boolean__",
  "__break__",
  "__class__",
  "__double__",
  "__else__",
  "__extends__",
  "__for__",
  "__if__",
  "__implements__",
  "__int__",
  "__interface__",
  "__newarray__",
  "__println__",
  "__readln__",
  "__return__",
  "__string__",
  "__void__",
  "__while__",
  "__plus__",
  "__minus__",
  "__multiplication__",
  "__division__",
  "__mod__",
  "__less__",
  "__lessequal__",
  "__greater__",
  "__greaterequal__",
  "__equal__",
  "__notequal__",
  "__and__",
  "__or__",
  "__not__",
  "__assignop__",
  "__comma__",
  "__semicolon__",
  "__period__",
  "__uminus__",
  "__leftparen__",
  "__rightparen__",
  "__leftbracket__",
  "__rightbracket__",
  "__leftbrace__",
  "__rightbrace__",
  "__intconstant__",
  "__doubleconstant__",
  "__stringconstant__",
  "__booleanconstant__",
  "__id__"
  };
}

